### ISSUE TITLE
Change cursor when interacting with disabled elements

### ISSUE THREAD

**Issue by swarmukhdefault** [dynatrace-oss/barista#2608]
# Bug Report

## Expected Behavior

Hovering over any disabled item (button, tab, input) should show a cursor style indicating forbidden interaction

## Current Behavior

Hovering over any disabled item (button, tab, input) doesn't show a `not-allowed` cursor

## Possible Solution

```css
/* Not sure about the exact selector(s) in this case */

element[disabled], .disabled {
  cursor: not-allowed;
  pointer-events: none; /* optional */
}
```

## Steps to Reproduce

1. Hover over any disabled item
2. Cursor remains as `pointer`

## Context (Environment)

As much as I appreaciate the focus on accessibility, I believe this small chagne should further enhance it in cases where a non-reflective monitor is used where-in colour contrast is not that great to distinguish that the control item under the current cursor position is active or not.

### Used Versions:

- **node**: 14.20.0
- **npm**: 
- **typescript**: 4.7.4
- **angular**: 14.1.1
- **@angular/cdk**: 13.3.9
- **@dynatrace/barista-components**: 10.7.5
